print("Hello GitHub")
print("I am learning Git")
print("This is my feature branch")
print('I am practicing Git and GitHub')
print("Login feature is being developed")
print("Change made directly on GitHub")
print("Change made from test branch")
print("Change made from master branch")
print("New change on master")
